### ISSUE TITLE
gen.py这个文件现在找不到了

### ISSUE THREAD

**Issue by Aquarian-Age** [zhangpf/fuchsia-docs-zh-CN#2]
[构建Fuchsia](https://github.com/zhangpf/fuchsia-docs-zh-CN/blob/master/build_system.md)
运行构建的时候
gen.py这个文件现在找不到了
编译完了内核之后
再运行>./scripts/build-zircon-x64
然后就不知道怎么弄了 请教下面怎么弄呢 谢谢

**Comment by zhangpf** [comment]
通过gen.py进行编译的方式我还没测试过，而且这个文档我还没来得及更新。
推荐使用[getting_started](https://github.com/zhangpf/fuchsia-docs-zh-CN/blob/master/getting_started.md)来进行编译和运行。

**Comment by Aquarian-Age** [comment]
@zhangpf  实际上官方的说法fx set x86-64 在makefile里面是没有这个选项的只有x64选择 如果用fx set x86-64我这里输出的是fx的help内容 而fx set x64运行起来就是出现错误了
````
六 4月 14|09:27|0:>fx set x64
+ /home/xuan/src/fuchsia/buildtools/gn gen out/x64 --check '--args=target_cpu="x64" fuchsia_packages=["topaz/packages/default",]'
ERROR at //build/gn/BUILD.gn:26:1: Script returned non-zero exit code.
exec_script("//build/zircon/create_gn_rules.py",
^----------
Current dir: /home/xuan/src/fuchsia/out/x64/
Command: /usr/bin/env -- /home/xuan/src/fuchsia/build/zircon/create_gn_rules.py --out /home/xuan/src/fuchsia/zircon/public --staging /home/xuan/src/fuchsia/out/x64/zircon-gn --zircon-user-build /home/xuan/src/fuchsia/out/build-zircon/build-${target_cpu} --zircon-tool-build /home/xuan/src/fuchsia/out/build-zircon
Returned 1 and printed out:

makefile:35: recipe for target 'packages' failed

stderr:

which: no ./prebuilt/downloads/gcc/bin/x86_64-elf-gcc in ((null))
kernel/arch/x86/toolchain.mk:18: *** cannot find toolchain, please set ARCH_x86_64_TOOLCHAIN_PREFIX or add it to your path.  Stop.
make: *** [packages] Error 2
Traceback (most recent call last):
  File "/home/xuan/src/fuchsia/build/zircon/create_gn_rules.py", line 414, in <module>
    sys.exit(main())
  File "/home/xuan/src/fuchsia/build/zircon/create_gn_rules.py", line 358, in main
    subprocess.check_call(make_args, cwd=ZIRCON_ROOT, env=env)
  File "/usr/lib64/python2.7/subprocess.py", line 186, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['make', 'packages', 'BUILDDIR=/home/xuan/src/fuchsia/out/x64/zircon-gn']' returned non-zero exit status 2
````

**Comment by zhangpf** [comment]
Fixed replace x86_64 to x64(#1).
